import { Vehicle } from "../../interfaces/interfaces";

export const vehiclesMockData: Vehicle[] = [
  {
    id: 1,
    vehicle_name: "KDA 1368 Toyota Hilux",
    capacity: 5,
    vehicle_type: "Pickup Truck",
    vehicle_image: require("../../../assets/toyota-hilux.jpg"),
    status: "On Trip",
    isVip: false,
  },
  {
    id: 2,
    vehicle_name: "KCU 2522 Montero Sport",
    capacity: 7,
    vehicle_type: "SUV",
    vehicle_image: require("../../../assets/mitsubishi-montero.jpg"),
    status: "Available",
    isVip: true,
  },
  {
    id: 3,
    vehicle_name: "KAB 2855 Fortuner",
    capacity: 7,
    vehicle_type: "SUV",
    vehicle_image: require("../../../assets/fortuner.jpg"),
    status: "On Trip",
    isVip: false,
  },
  {
    id: 4,
    vehicle_name: "KYZ 2069 Toyota Hiace",
    capacity: 15,
    vehicle_type: "Van",
    vehicle_image: require("../../../assets/toyota-hiace.png"),
    status: "Available",
    isVip: true,
  },
  {
    id: 5,
    vehicle_name: "KDA 1368 Toyota Hilux",
    capacity: 5,
    vehicle_type: "Pickup Truck",
    vehicle_image: require("../../../assets/toyota-hilux.jpg"),
    status: "Unavailable",
    isVip: false,
  },
  {
    id: 6,
    vehicle_name: "KYZ 2069 Toyota Hiace",
    capacity: 15,
    vehicle_type: "Van",
    vehicle_image: require("../../../assets/toyota-hiace.png"),
    status: "Unavailable",
    isVip: false,
  },
];

export const fetchedPendingData = [
  {
    request_number: "02",
    travel_date: "08/17/2023",
    vehicle: "Ford Ranger",
    status: "Pending",
    requester_name: "John Doe",
    office_dept: "CITC",
    number_of_passenger: 2,
    passenger_name: ["Alice", "Bob"],
    destination: "Conference Center",
    time: "09:00 AM",
    purpose: "Attend meeting",
    urgent: false,
  },
  {
    request_number: "03",
    travel_date: "08/18/2023",
    vehicle: "Nissan Navara",
    status: "Pending",
    requester_name: "Jane Smith",
    office_dept: "COT",
    number_of_passenger: 1,
    passenger_name: ["Eve"],
    destination: "Client Office",
    time: "02:30 PM",
    purpose: "Sales visit",
    urgent: false,
  },
  {
    request_number: "04",
    travel_date: "08/19/2023",
    vehicle: "Chevrolet Colorado",
    status: "Pending",
    requester_name: "Michael Johnson",
    office_dept: "CEA",
    number_of_passenger: 3,
    passenger_name: ["Grace", "Daniel", "Sophia"],
    destination: "Team Building Retreat",
    time: "08:00 AM",
    purpose: "Team event",
    urgent: true,
  },
  {
    request_number: "05",
    travel_date: "08/20/2023",
    vehicle: "Honda Ridgeline",
    status: "Pending",
    requester_name: "Emma Davis",
    office_dept: "CSM",
    number_of_passenger: 1,
    passenger_name: ["Oliver"],
    destination: "Training Workshop",
    time: "10:00 AM",
    purpose: "Skill development",
    urgent: false,
  },
  {
    request_number: "06",
    travel_date: "08/21/2023",
    vehicle: "Mitsubishi Triton",
    status: "Pending",
    requester_name: "William Wilson",
    office_dept: "CSTE",
    number_of_passenger: 2,
    passenger_name: ["Sophia", "Liam"],
    destination: "Vendor Meeting",
    time: "11:30 AM",
    purpose: "Negotiations",
    urgent: false,
  },
  {
    request_number: "07",
    travel_date: "08/22/2023",
    vehicle: "Isuzu D-Max",
    status: "Pending",
    requester_name: "Olivia Martin",
    office_dept: "SHS",
    number_of_passenger: 4,
    passenger_name: ["Noah", "Ava", "William", "Emma"],
    destination: "Company Retreat",
    time: "08:00 AM",
    purpose: "Team bonding",
    urgent: false,
  },
  {
    request_number: "08",
    travel_date: "08/23/2023",
    vehicle: "Volkswagen Amarok",
    status: "Pending",
    requester_name: "Liam Johnson",
    office_dept: "CITC",
    number_of_passenger: 1,
    passenger_name: ["Oliver"],
    destination: "Client Presentation",
    time: "03:00 PM",
    purpose: "Business meeting",
    urgent: false,
  },
  {
    request_number: "09",
    travel_date: "08/24/2023",
    vehicle: "Mazda BT-50",
    status: "Pending",
    requester_name: "Sophia Taylor",
    office_dept: "COT",
    number_of_passenger: 2,
    passenger_name: ["Liam", "Ava"],
    destination: "Supplier Visit",
    time: "10:30 AM",
    purpose: "Vendor assessment",
    urgent: false,
  },
  {
    request_number: "10",
    travel_date: "08/25/2023",
    vehicle: "GMC Canyon",
    status: "Pending",
    requester_name: "Daniel Brown",
    office_dept: "CEA",
    number_of_passenger: 3,
    passenger_name: ["Noah", "Emma", "William"],
    destination: "Training Workshop",
    time: "09:00 AM",
    purpose: "Professional development",
    urgent: false,
  },
  {
    request_number: "11",
    travel_date: "08/26/2023",
    vehicle: "RAM 1500",
    status: "Pending",
    requester_name: "Ava Martinez",
    office_dept: "CSM",
    number_of_passenger: 1,
    passenger_name: ["Oliver"],
    destination: "Client Meeting",
    time: "02:00 PM",
    purpose: "Project discussion",
    urgent: false,
  },
];

export const fetchedApprovedData = [
  {
    request_number: "10",
    travel_date: "April 16, 2024",
    vehicle: "Toyota Hilux",
    status: "Approved",
    requester_name: "Alex Brown",
    office_dept: "COT",
    number_of_passenger: 3,
    passenger_name: ["Grace", "Daniel", "Sophia"],
    destination: "Team Building Retreat",
    time: "08:00 AM",
    purpose: "Team event",
    urgent: false,
  },
  {
    request_number: "02",
    travel_date: "August 17, 2023",
    vehicle: "Ford Ranger",
    status: "Approved",
    requester_name: "John Doe",
    office_dept: "CITC",
    number_of_passenger: 2,
    passenger_name: ["Alice", "Bob"],
    destination: "Conference Center",
    time: "09:00 AM",
    purpose: "Attend meeting",
    urgent: false,
  },
  {
    request_number: "03",
    travel_date: "August 18, 2023",
    vehicle: "Nissan Navara",
    status: "Approved",
    requester_name: "Jane Smith",
    office_dept: "COT",
    number_of_passenger: 1,
    passenger_name: ["Eve"],
    destination: "Client Office",
    time: "02:30 PM",
    purpose: "Sales visit",
    urgent: false,
  },
  {
    request_number: "04",
    travel_date: "August 19, 2023",
    vehicle: "Chevrolet Colorado",
    status: "Approved",
    requester_name: "Michael Johnson",
    office_dept: "CEA",
    number_of_passenger: 3,
    passenger_name: ["Grace", "Daniel", "Sophia"],
    destination: "Team Building Retreat",
    time: "08:00 AM",
    purpose: "Team event",
    urgent: false,
  },
];

export const fetchedCanceledData = [
  {
    request_number: "10",
    travel_date: "April 16, 2024",
    vehicle: "Toyota Hilux",
    status: "Canceled",
    requester_name: "Michael Johnson",
    office_dept: "CEA",
    number_of_passenger: 1,
    passenger_name: ["Olivia"],
    destination: "Workshop",
    time: "10:00 AM",
    purpose: "Training session",
    urgent: false,
  },
];

export const fetchedDeclinedData = [
  {
    request_number: "10",
    travel_date: "April 16, 2024",
    vehicle: "Toyota Hilux",
    status: "Declined",
    requester_name: "Sophie Martinez",
    office_dept: "COT",
    number_of_passenger: 2,
    passenger_name: ["Liam", "Ava"],
    destination: "Supplier Meeting",
    time: "11:30 AM",
    purpose: "Negotiations",
    urgent: false,
  },
  {
    request_number: "10",
    travel_date: "August 25, 2023",
    vehicle: "GMC Canyon",
    status: "Declined",
    requester_name: "Daniel Brown",
    office_dept: "CEA",
    number_of_passenger: 3,
    passenger_name: ["Noah", "Emma", "William"],
    destination: "Training Workshop",
    time: "09:00 AM",
    purpose: "Professional development",
    urgent: false,
  },
  {
    request_number: "11",
    travel_date: "August 26, 2023",
    vehicle: "RAM 1500",
    status: "Declined",
    requester_name: "Ava Martinez",
    office_dept: "CSM",
    number_of_passenger: 1,
    passenger_name: ["Oliver"],
    destination: "Client Meeting",
    time: "02:00 PM",
    purpose: "Project discussion",
    urgent: false,
  },
];

export const todayMockData = [
  {
    trip_number: 1,
    time: "08:00 AM",
    destination: "Office",
  },
  {
    trip_number: 2,
    time: "09:30 AM",
    destination: "Client Meeting",
  },
  {
    trip_number: 3,
    time: "12:15 PM",
    destination: "Lunch",
  },
  {
    trip_number: 4,
    time: "03:45 PM",
    destination: "Supplier Visit",
  },
  {
    trip_number: 5,
    time: "06:00 PM",
    destination: "Home",
  },
];
