import { Vehicle } from "../../interfaces/interfaces";

export const vehiclesMockData: Vehicle[] = [
  {
    id: 1,
    vehicle_name: "KDA 1368 Toyota Hilux",
    capacity: 5,
    vehicle_type: "Pickup Truck",
    vehicle_image: require("../../../assets/toyota-hilux.jpg"),
    status: "On Trip",
    isVip: false,
  },
  {
    id: 2,
    vehicle_name: "KCU 2522 Montero Sport",
    capacity: 7,
    vehicle_type: "SUV",
    vehicle_image: require("../../../assets/mitsubishi-montero.jpg"),
    status: "Available",
    isVip: true,
  },
  {
    id: 3,
    vehicle_name: "KAB 2855 Fortuner",
    capacity: 7,
    vehicle_type: "SUV",
    vehicle_image: require("../../../assets/fortuner.jpg"),
    status: "On Trip",
    isVip: false,
  },
  {
    id: 4,
    vehicle_name: "KYZ 2069 Toyota Hiace",
    capacity: 15,
    vehicle_type: "Van",
    vehicle_image: require("../../../assets/toyota-hiace.png"),
    status: "Available",
    isVip: true,
  },
  {
    id: 5,
    vehicle_name: "KDA 1368 Toyota Hilux",
    capacity: 5,
    vehicle_type: "Pickup Truck",
    vehicle_image: require("../../../assets/toyota-hilux.jpg"),
    status: "Unavailable",
    isVip: false,
  },
  {
    id: 6,
    vehicle_name: "KYZ 2069 Toyota Hiace",
    capacity: 15,
    vehicle_type: "Van",
    vehicle_image: require("../../../assets/toyota-hiace.png"),
    status: "Unavailable",
    isVip: false,
  },
];
